function in_array(needle, haystack, argStrict) {var key = '',strict = !! argStrict;
  if (strict) {for (key in haystack) {if (haystack[key] === needle) {return true;}}
  } else {for (key in haystack) {if (haystack[key] == needle) {return true;}}}return false;}
var last = [
['Head-Tracker','h/head-tracker.html',''],
['Eye-Tracker','e/eye-tracker.html',''],
['Intranet','i/intranet.html',''],
['Extrusion','e/extrusion.html',''],
['Plug-In','p/plug-in.html',''],
['Energy-Star','e/energy-star.html',''],
['E-Mail Postfach','e/e-mail-postfach.html',''],
['HDTV','h/hdtv.html',''],
['HD Ready','h/hd-ready.html',''],
['Supersampling','s/supersampling.html','']
];
var sites = [
['Abfragesprache','a/abfragesprache.html',''],
['Account','a/account.html',''],
['ACM','a/acm.html',''],
['Ada','a/ada.html',''],
['Adabas','a/adabas.html',''],
['Add-on','a/add-on.html',''],
['Adressierung','a/adressierung.html',''],
['Adressraum','a/adressraum.html',''],
['Adressregister','a/adressregister.html',''],
['Aiken-Code','a/aiken-howard-hathaway.html',''],
['Aiken, Howard Hathaway','a/aiken-howard-hathaway.html',''],
['Akkumulator','a/akkumulator.html',''],
['Aktiv','a/aktiv.html',''],
['Aktiver Bildschirm','a/aktiver-bildschirm.html',''],
['Aktiv-Lautsprecher','a/aktiv-lautsprecher.html',''],
['Algol','a/algol.html',''],
['Algorithmus','a/algorithmus.html',''],
['Aliasing','a/aliasing.html',''],
['Alphanumerisch','a/alphanumerisch.html',''],
['Alphaversion','a/alphaversion.html',''],
['ALU','a/alu.html',''],
['A.M.','a/a-m.html',''],
['Analog','a/analog.html',''],
['Analog-Digital-Wandler','a/analog-digital-wandler.html',''],
['Analog-Signal','a/analog-signal.html',''],
['And','a/and.html',''],
['Animation','a/animation.html',''],
['ANSI','a/ansi.html',''],
['ANSI-Code','a/ansi-code.html',''],
['ANSI-Datei','a/ansi-datei.html',''],
['ANSI-Zeichensatz','a/ansi-zeichensatz.html',''],
['Anti-Aliasing','a/anti-aliasing.html',''],
['Antivirensoftware','a/antivirensoftware.html',''],
['Anweisung','a/anweisung.html',''],
['Anwendungsprogramm','a/anwendungsprogramm.html',''],
['API','a/api.html',''],
['APL','a/apl.html',''],
['APPC','a/appc.html',''],
['Application-Server','a/application-server.html',''],
['Äquivalenz','a/aequivalenz.html',''],
['Arbeitsspeicher','a/arbeitsspeicher.html',''],
['Archivierung','a/archivierung.html',''],
['Argument','a/argument.html',''],
['Arithmetischer Überlauf','a/arithmetischer-ueberlauf.html',''],
['Array','a/array.html',''],
['ASCII','a/ascii.html',''],
['ASCII-Code','a/ascii-code.html',''],
['ASCII-Zeichensatz','a/ascii-zeichensatz.html',''],
['ASIC','a/asic.html',''],
['Assembler','a/assembler.html',''],
['Assistent','a/assistent.html',''],
['Asynchron','a/asynchron.html',''],
['AT-Bus','a/at-bus.html',''],
['ATM','a/atm.html',''],
['Auflösung','a/aufloesung.html',''],
['Ausführbares Programm','a/ausfuehrbares-programm.html',''],
['Auslagerungsdatei','a/auslagerungsdatei.html',''],
['Auto Answer','a/auto-answer.html',''],
['Autoexec','a/autoexec.html',''],
['AWK','a/awk.html',''],
['Abstrakte Klasse','http://www.bullhost.de/a/abstrakte-klasse.html',''],
['Absturz','a/absturz.html',''],
['Access','a/access.html',''],
['Administrator','a/administrator.html',''],
['AGP','a/agp.html',''],
['Aktiendiagramm','a/aktiendiagramm.html',''],
['Alt','a/alt.html',''],
['Alt-Gr','a/alt-gr.html',''],
['Animationsprogramm','a/animationsprogramm.html',''],
['Ankerzelle','a/ankerzelle.html',''],
['Anklopfen','a/anklopfen.html',''],
['Anschlagdrucker','a/anschlagdrucker.html',''],
['Anschlagfreier Drucker','a/anschlagfreier-drucker.html',''],
['Anwendungsschicht','a/anwendungsschicht.html',''],
['Apple','a/apple.html',''],
['Apple II','a/apple-2.html',''],
['AppleShare','a/appleshare.html',''],
['AppleTalk','a/appletalk.html',''],
['Application Layer','a/application-layer.html',''],
['Arbeitsstation','a/arbeitsstation.html',''],
['Archie','a/archie.html',''],
['Archiv','a/archiv.html',''],
['Archiv-Attribut','a/archiv-attribut.html',''],
['Arcnet','a/arcnet.html',''],
['Arithmetischer Coprozessor','a/arithmetischer-coprozessor.html',''],
['ARPANET','a/arpanet.html',''],
['ASCII-Datei','a/ascii-datei.html',''],
['ASP','a/asp.html',''],
['Assem. Programmiersprache','a/assemblernahe-programmiersprache.html',''],
['Assemblieren','a/assemblieren.html',''],
['Assoziative Bemaßung','a/assoziative-bemassung.html',''],
['Asterisk','a/asterisk.html',''],
['Asymm. Multiprozessorsystem','a/asymmetrisches-multiprozessorsystem.html',''],
['AT','a/at.html',''],
['Atom','a/atom.html',''],
['Attribut','a/attribut.html',''],
['Audiotext','a/audiotext.html',''],
['Auditing','a/auditing.html',''],
['Aufrastern','a/aufrastern.html',''],
['Aufwärtskompatibel','a/aufwaertskompatibel.html',''],
['Ausdruck','a/ausdruck.html',''],
['Ausführbare Datei','a/ausfuehrbare-datei.html',''],
['Ausgabegerät','a/ausgabegeraet.html',''],
['Ausrichtung','a/ausrichtung.html',''],
['Ausschneiden','a/ausschneiden.html',''],
['Austastlücke','a/austastluecke.html',''],
['Auswahlschalter','a/auswahlschalter.html',''],
['AutoCAD','a/autocad.html',''],
['Autodesk','a/autodesk.html',''],
['AUTOEXEC.BAT','a/autoexec-bat.html',''],
['Autoformat','a/autoformat.html',''],
['Autokorrektur','a/autokorrektur.html',''],
['Automatische Bemaßung','a/automatische-bemassung.html',''],
['Automatischer Einzelblatteinzug','a/automatischer-einzelblatteinzug.html',''],
['Auto-Parkeinrichtung','a/auto-parkeinrichtung.html',''],
['Autorensystem','a/autorensystem.html',''],
['Autosketch','a/autosketch.html',''],
['Autotracing','a/autotracing.html',''],
['A/UX','a/a-ux.html',''],
['AVI-Format','a/avi-format.html',''],
['Absoluter Bezug','a/absoluter-bezug.html',''],
['AC97','a/ac97.html',''],
['Access Point','a/access-point.html',''],
['ActiveSync-Verfahren','a/activesync-verfahren.html',''],
['ActiveX','a/activex.html',''],
['Add-In','a/add-in.html',''],
['AdImpressions','a/adimpressions.html',''],
['Adware','a/adware.html',''],
['Agent','a/agent.html',''],
['Aktive Kühler','a/aktive-kuehler.html',''],
['Alpha-Blending','a/alpha-blending.html',''],
['Anisotropische Beleuchtung','a/anisotropische-beleuchtung.html',''],
['Anisotropische Filterung','a/anisotropische-filterung.html',''],
['Anlagenanschluss','a/anlagenanschluss.html',''],
['Anker','a/anker.html',''],
['Anschaltgebühr','a/anschaltgebuehr.html',''],
['Ansicht','a/ansicht.html',''],
['Antonym','a/antonym.html',''],
['Application Sharing','a/application-sharing.html',''],
['Arbeitsplatz','a/arbeitsplatz.html',''],
['Architektur','a/architektur.html',''],
['ASF-Datei','a/asf-datei.html',''],
['asym. Verschlüsselung','a/asymmetrische-verschluesselung.html',''],
['ATA','a/ata.html',''],
['Athlon','a/athlon.html',''],
['ATI-Radeon','a/ati-radeon.html',''],
['AT&T','a/at-t.html',''],
['Attachment','a/attachment.html',''],
['Authenzität','a/authenzitaet.html',''],
['Autochanger','a/autochanger.html',''],
['AutoPlay-Funktion','a/autoplay-funktion.html',''],
['Autoscan','a/autoscan.html',''],
['Autostart','a/autostart.html',''],
['Autovervollständigen','a/autovervollstaendigen.html',''],
['Backup','b/backup.html',''],
['Backup-Programm','b/backup-programm.html',''],
['Backup-Strategien','b/backup-strategien.html',''],
['Backus-Naur-Form','b/backus-naur-form.html',''],
['Bandbreite','b/bandbreite.html',''],
['Banyan Vines','b/banyan-vines.html',''],
['Basisadresse','b/basisadresse.html',''],
['Basisbandnetz','b/basisbandnetz.html',''],
['Baud','b/baud.html',''],
['BCD','b/bcd.html',''],
['BCPl','b/bcpl.html',''],
['Bedienungsfehler','b/bedienungsfehler.html',''],
['Bedingte Schleife','b/bedingte-schleife.html',''],
['Bedingung','b/bedingung.html',''],
['Beendigungscode','b/beendigungscode.html',''],
['Befehlsprozessor','b/befehlsprozessor.html',''],
['Benutzername','b/benutzername.html',''],
['Benutzeroberfläche','b/benutzeroberflaeche.html',''],
['Benutzerprofil','b/benutzerprofil.html',''],
['Beschreibungssprache','b/beschreibungssprache.html',''],
['Betaversion','b/betaversion.html',''],
['Betriebssystem','b/betriebssystem.html',''],
['Betriebssystemerweiterung','b/betriebssystemerweiterung.html',''],
['Bézier-Kurve','b/bezier-kurve.html',''],
['BGI-Treiber','b/bgi-treiber.html',''],
['Bibliothek','b/bibliothek.html',''],
['Bildbearbeitungsprogramm','b/bildbearbeitungsprogramm.html',''],
['Bildschirm','b/bildschirm.html',''],
['Bildschirmkarte','b/bildschirmkarte.html',''],
['Bildschirmmaske','b/bildschirmmaske.html',''],
['Bildschirmschoner','b/bildschirmschoner.html',''],
['Bildwiederholfrequenz','b/bildwiederholfrequenz.html',''],
['Bi-Modem','b/bi-modem.html',''],
['Binäre Addition','b/binaere-addition.html',''],
['Binärkompatibel','b/binaerkompatibel.html',''],
['Binärsystem','b/binaersystem.html',''],
['Bindery','b/bindery.html',''],
['Bios','b/bios.html',''],
['Bit','b/bit.html',''],
['Bitmap-Grafik','b/bitmap-grafik.html',''],
['BLOB','b/blob.html',''],
['Bluebox','b/bluebox.html',''],
['BNC','b/bnc.html',''],
['Boolesche Algebra','b/boolesche-algebra.html',''],
['Boolesche Variable','b/boolesche-variable.html',''],
['Bootsektor','b/bootsektor.html',''],
['Bootstrap-Loader','b/bootstrap-loader.html',''],
['Bootsektor-Virus','b/bootsektor-virus.html',''],
['Bottom-up-Methode','b/bottom-up-methode.html',''],
['Breakpoint','b/breakpoint.html',''],
['Breitbandnetz','b/breitbandnetz.html',''],
['Browser','b/browser.html',''],
['Bubblesort','b/bubblesort.html',''],
['Bug','b/bug.html',''],
['Burn-in-Test','b/burn-in-test.html',''],
['Bus','b/bus.html',''],
['Busbreite','b/busbreite.html',''],
['Bus-Mastering','b/bus-mastering.html',''],
['Bus-Topologie','b/bus-topologie.html',''],
['Byte','b/byte.html',''],
['Backbone','b/backbone.html',''],
['Backpropagation','b/backpropagation.html',''],
['Backtracking','b/backtracking.html',''],
['Balkeniagramm','b/balkeniagramm.html',''],
['Bank Switching','b/bank-switching.html',''],
['Banner','b/banner.html',''],
['Basic','b/basic.html',''],
['Barebone','b/barebone.html',''],
['BAT-Format','b/bat-format.html',''],
['Baum-Topologie','b/baum-topologie.html',''],
['BEO-RAM','b/beo-ram.html',''],
['Beep-Coes','b/beep-coes.html',''],
['Befehlssatz','b/befehlssatz.html',''],
['Belichter','b/belichter.html',''],
['Bemaßung','b/bemassung.html',''],
['Benchmark','b/benchmark.html',''],
['Bernoulli-Box','b/bernoulli-box.html',''],
['Betatest','b/betatest.html',''],
['Betatester','b/betatester.html',''],
['Bezeichner','b/bezeichner.html',''],
['Biirektional','b/biirektional.html',''],
['Bilschirmiagonale','b/bilschirmiagonale.html',''],
['Biometrie','b/biometrie.html',''],
['Bionik','b/bionik.html',''],
['Bit-Plane','b/bit-plane.html',''],
['Bit/s','b/bit-s.html',''],
['Bit-String','b/bit-string.html',''],
['Bitübertragungsschicht','b/bituebertragungsschicht.html',''],
['Blank','b/blank.html',''],
['Blintext','b/blintext.html',''],
['Blockgrafik','b/blockgrafik.html',''],
['Blockoperationen','b/blockoperationen.html',''],
['Blocksatz','b/blocksatz.html',''],
['Bluetooth','b/bluetooth.html',''],
['BMP-Format','b/bmp-format.html',''],
['Bohr-Bug','b/bohr-bug.html',''],
['Bol','b/bol.html',''],
['Bombe','b/bombe.html',''],
['Bookmark','b/bookmark.html',''],
['Bookware','b/bookware.html',''],
['Bootblock','b/bootblock.html',''],
['Booten','b/booten.html',''],
['Borlan','b/borlan.html',''],
['Bourne-Shell','b/bourne-shell.html',''],
['Bpp','b/bpp.html',''],
['Brainware','b/brainware.html',''],
['Brige','b/brige.html',''],
['Brige Boar','b/brige-boar.html',''],
['Browse-Mous','b/browse-mous.html',''],
['Brute-Force-Verfahren','b/brute-force-verfahren.html',''],
['BS-Unix','b/bs-unix.html',''],
['BTX','b/btx.html',''],
['Bulk-Ware','b/bulk-ware.html',''],
['Bunesatenschutzgesetz','b/bunesatenschutzgesetz.html',''],
['Bunling','b/bunling.html',''],
['Bunsteg','b/bunsteg.html',''],
['Burst-Mous','b/burst-mous.html',''],
['Button','b/button.html',''],
['Byte-Variable','b/byte-variable.html',''],
['BZT','b/bzt.html',''],
['B2B','b/b2b.html',''],
['B2C','b/b2c.html',''],
['B2G','b/b2g.html',''],
['Back-End-Prozessor','b/back-end-prozessor.html',''],
['Backdoor','b/backdoor.html',''],
['Backface Culling','b/backface-culling.html',''],
['Back Orifice','b/back-orifice.html',''],
['Backplane','b/backplane.html',''],
['Backslash','b/backslash.html',''],
['Backspace-Taste','b/backspace-taste.html',''],
['Banias','b/banias.html',''],
['BAPT','b/bapt.html',''],
['Barcode','b/barcode.html',''],
['Basisanschluss','b/basisanschluss.html',''],
['Basisbandübertragung','b/basisbanduebertragung.html',''],
['BCC','b/bcc.html',''],
['BDC','b/bdc.html',''],
['Beamer','b/beamer.html',''],
['Beleuchtungsstärke','b/beleuchtungsstaerke.html',''],
['Beowulf','b/beowulf.html',''],
['Bi-Endian','b/bi-endian.html',''],
['Big-Endian','b/big-endian.html',''],
['Bildbearbeitung','b/bildbearbeitung.html',''],
['Bildkompression','b/bildkompression.html',''],
['Bildlaufleiste','b/bildlaufleiste.html',''],
['Bildtelefon','b/bildtelefon.html',''],
['Bildtelefonie','b/bildtelefonie.html',''],
['Bildtrommel','b/bildtrommel.html',''],
['Bilineare Filterung','b/bilineare-filterung.html',''],
['Binary Chop','b/binary-chop.html',''],
['Binary Term','b/binary-term.html',''],
['Binary Transfer','b/binary-transfer.html',''],
['Bindungszeit','b/bindungszeit.html',''],
['BinHex','b/binhex.html',''],
['Biometrisches System','b/biometrisches-system.html',''],
['Bistabil','b/bistabil.html',''],
['Bistabiler Multivibrator','b/bistabiler-multivibrator.html',''],
['Bistabiler Schaltkreis','b/bistabiler-schaltkreis.html',''],
['BiSync','b/bisync.html',''],
['Bit-Block','b/bit-block.html',''],
['Bitblocktransfer','b/bitblocktransfer.html',''],
['Bitdichte','b/bitdichte.html',''],
['Bit-Flipping','b/bit-flipping.html',''],
['Bit-Manipulation','b/bit-manipulation.html',''],
['Bit. Übertragungsprotokoll','b/bitorientiertes-uebertragungsprotokoll.html',''],
['Bitrate','b/bitrate.html',''],
['Bit-Slice-Prozessor','b/bit-slice-prozessor.html',''],
['Bitstrom','b/bitstrom.html',''],
['Bittiefe','b/bittiefe.html',''],
['Bit-Übertragungsrate','b/bit-uebertragungsrate.html',''],
['Bitweise parallel','b/bitweise-parallel.html',''],
['Bitweise seriell','b/bitweise-seriell.html',''],
['B-Kanal','b/b-kanal.html',''],
['BKZ','b/bkz.html',''],
['Blackberry','b/blackberry.html',''],
['Blackbox','b/blackbox.html',''],
['Bladeserver','b/bladeserver.html',''],
['Blanking','b/blanking.html',''],
['Blindfarbe','b/blindfarbe.html',''],
['Blip','b/blip.html',''],
['Blackout','b/blackout.html',''],
['Blog','b/blog.html',''],
['Blowfish','b/blowfish.html',''],
['Blu-Ray Disc','b/blu-ray-disc.html',''],
['Blue Book','b/blue-book.html',''],
['Body-Scanning','b/body-scanning.html',''],
['Boot-CD','b/boot-cd.html',''],
['Bootdiskette','b/bootdiskette.html',''],
['BOOTP','b/bootp.html',''],
['Bootmanager','b/bootmanager.html',''],
['Bozo-Filter','b/bozo-filter.html',''],
['Bpi','b/bpi.html',''],
['Bps','b/bps.html',''],
['Brain Dump','b/brain-dump.html',''],
['Breakout-Box','b/breakout-box.html',''],
['Breitbandübertragung','b/breitbanduebertragung.html',''],
['Bridge Disc','b/bridge-disc.html',''],
['Bridgeware','b/bridgeware.html',''],
['Broadcast','b/broadcast.html',''],
['Broadcast-Storm','b/broadcast-storm.html',''],
['Brouter','b/brouter.html',''],
['Brownout','b/brownout.html',''],
['BRS','b/brs.html',''],
['Btree','b/btree.html',''],
['BTT','b/btt.html',''],
['Bump-Mapping','b/bump-mapping.html',''],
['Burst-Cache','b/burst-cache.html',''],
['Burst-Transmission','b/burst-transmission.html',''],
['Bypass','b/bypass.html',''],
['Byte. Übertragungsprotokoll',''],['b/byteorientiertes-uebertragungsprotokoll.html',''],
['C++','c/c-plus-plus.html',''],
['C2-Sicherheitsrichtlinien','c/c2-sicherheitsrichtlinien.html',''],
['C2C','c/c2c.html',''],
['CA','c/ca.html',''],
['Cache','c/cache.html',''],
['Cache-Controller','c/cache-controller.html',''],
['CAD','c/cad.html',''],
['CADAM','c/cadam.html',''],
['CAD/CAM','c/cad-cam.html',''],
['Caddy','c/caddy.html',''],
['CAD-Programm','c/cad-programm.html',''],
['CAE','c/cae.html',''],
['CallBack','c/callback.html',''],
['Call-Back-Modem','c/call-back-modem.html',''],
['CALL-Befehl','c/call-befehl.html',''],
['Call by Call','c/call-by-call.html',''],
['Call Center','c/call-center.html',''],
['Calling-Ton','c/calling-ton.html',''],
['Callthrough','c/callthrough.html',''],
['CAM','c/cam.html',''],
['CAMAC','c/camac.html',''],
['Camino','c/camino.html',''],
['Cancelbot','c/cancelbot.html',''],
['CAO','c/cao.html',''],
['CAP','c/cap.html',''],
['Captain Crunch','c/captain-crunch.html',''],
['CAQ','c/caq.html',''],
['CAR','c/car.html',''],
['Careware','c/careware.html',''],
['Carrier','c/carrier.html',''],
['CAS','c/cas.html',''],
['CASE','c/case.html',''],
['Case-Modding','c/case-modding.html',''],
['CAUCE','c/cauce.html',''],
['CAV-Verfahren','c/cav-verfahren.html',''],
['CB','c/cb.html',''],
['CBR','c/cbr.html',''],
['CC','c/cc.html',''],
['CCD','c/ccd.html',''],
['CCITT','c/ccitt.html',''],
['CD-Brenner','c/cd-brenner.html',''],
['CDFS','c/cdfs.html',''],
['CD-Laufwerk','c/cd-laufwerk.html',''],
['CD-ROM','c/cd-rom.html',''],
['CeBIT','c/cebit.html',''],
['Celeron','c/celeron.html',''],
['Centrino-Technologie','c/centrino-technologie.html',''],
['Centronics-Schnittstelle','c/centronics-schnittstelle.html',''],
['CEPT','c/cept.html',''],
['CGA','c/cga.html',''],
['Chat','c/chat.html',''],
['Cheat','c/cheat.html',''],
['Chip','c/chip.html',''],
['Chipgehäuse','c/chipgehaeuse.html',''],
['CIC','c/cic.html',''],
['Cicero','c/cicero.html',''],
['CIM','c/cim.html',''],
['CIS','c/cis.html',''],
['CISC-Prozessor','c/cisc-prozessor.html',''],
['ck-Trennung','c/ck-trennung.html',''],
['Cladding','c/cladding.html',''],
['Client','c/client.html',''],
['Client-Server-Architecktur','c/client-server-architektur.html',''],
['Client-Server-Netzwerk','c/client-server-netzwerk.html',''],
['Clipart','c/clipart.html',''],
['Clipboard','c/clipboard.html',''],
['Clipper','c/clipper.html',''],
['Clipping','c/clipping.html',''],
['Clone','c/clone.html',''],
['CLS','c/cls.html',''],
['Cluster','c/cluster.html',''],
['CLV-Verfahren','c/clv-verfahren.html',''],
['CMOS','c/cmos.html',''],
['CMS','c/cms.html',''],
['CMYK','c/cmyk.html',''],
['Cobol','c/cobol.html',''],
['Code','c/code.html',''],
['Codec','c/codec.html',''],
['Codeseite','c/codeseite.html',''],
['Code-Transformation','c/code-transformation.html',''],
['Color Cycling','c/color-cycling.html',''],
['Color Keying','c/color-keying.html',''],
['ColorSync','c/colorsync.html',''],
['COM','c/com.html',''],
['COM1','c/com-1.html',''],
['Comal','c/comal.html',''],
['Combo-Box','c/combo-box.html',''],
['Comdex','c/comdex.html',''],
['COMMAND.COM','c/command-com.html',''],
['CompactFlash-Karte','c/compactflash-karte.html',''],
['Compilat','c/compilat.html',''],
['Compile and go','c/compile-and-go.html',''],
['Compiler','c/compiler.html',''],
['Compiler-Bau','c/compiler-bau.html',''],
['Compiler-Direktive','c/compiler-direktive.html',''],
['Compiler-Sprache','c/compiler-sprache.html',''],
['Composite-Videosignal','c/composite-videosignal.html',''],
['Compound-Dokument','c/compound-dokument.html',''],
['Computer','c/computer.html',''],
['Computergenerationen','c/computergenerationen.html',''],
['Computerklassen','c/computerklassen.html',''],
['Computertomographie','c/computertomographie.html',''],
['CON','c/conn.html',''],
['Controller','c/controller.html',''],
['CORBA','c/corba.html',''],
['CorelDraw','c/coreldraw.html',''],
['Coretest','c/coretest.html',''],
['Counter','c/counter.html',''],
['Courier','c/courier.html',''],
['COW','c/cow.html',''],
['Cpi','c/cpi.html',''],
['Cpl','c/cpl.html',''],
['CPP-Format','c/cpp-format.html',''],
['CP/M','c/cp-m.html',''],
['Cps','c/cps.html',''],
['CPU','c/cpu.html',''],
['Cracker','c/cracker.html',''],
['Cracking','c/cracking.html',''],
['Crash-Recovery','c/crash-recovery.html',''],
['Crashtest','c/crashtest.html',''],
['CRC','c/crc.html',''],
['Crippleware','c/crippleware.html',''],
['Critical-Error-Handler','c/critical-error-handler.html',''],
['Cross-Assembler','c/cross-assembler.html',''],
['Cross-Compiler','c/cross-compiler.html',''],
['Cross-Referenz-Tabelle','c/cross-referenz-tabelle.html',''],
['CRT','c/crt.html',''],
['CSCW','c/cscw.html',''],
['CSMA/CD','c/csma-cd.html',''],
['CTS','c/cts.html',''],
['CUA','c/cua.html',''],
['CUI','c/cui.html',''],
['Cursor','c/cursor.html',''],
['Cursor-Tasten','c/cursor-tasten.html',''],
['Cut and Paste','c/cut-and-paste.html',''],
['Cyan','c/cyan.html',''],
['Cybersquatting','c/cybersquatting.html',''],
['D-Kanal','d/d-kanal.html',''],
['Daemon','d/daemon.html',''],
['Dämpfung','d/daempfung.html',''],
['Darstellungsschicht','d/darstellungsschicht.html',''],
['Data Link','d/data-link.html',''],
['Data Switch','d/data-switch.html',''],
['Datei','d/datei.html',''],
['Dateiattribut','d/dateiattribut.html',''],
['Dateiauswahlfenster','d/dateiauswahlfenster.html',''],
['Datei-Backup','d/datei-backup.html',''],
['Dateibelegungstabelle','d/dateibelegungstabelle.html',''],
['Dateierweiterung','d/dateierweiterung.html',''],
['Dateiformat','d/dateiformat.html',''],
['Datei-Manager','d/datei-manager.html',''],
['Dateiname','d/dateiname.html',''],
['Dateisystem','d/dateisystem.html',''],
['Dateiverwaltungsprogramm','d/dateiverwaltungsprogramm.html',''],
['Dateiverwaltungssystem','d/dateiverwaltungssystem.html',''],
['Dateizuordnungstabelle','d/dateizuordnungstabelle.html',''],
['Daten','d/daten.html',''],
['Datenabgleich','d/datenabgleich.html',''],
['Datenaustausch','d/datenaustausch.html',''],
['Datenbank','d/datenbank.html',''],
['Datenbestand','d/datenbestand.html',''],
['Datenbit','d/datenbit.html',''],
['Datenbus','d/datenbus.html',''],
['Datenfeld','d/datenfeld.html',''],
['Datenfeldtyp','d/datenfeldtyp.html',''],
['Datenflußplan','d/datenflussplan.html',''],
['Datenhandschuh','d/datenhandschuh.html',''],
['Datenmaske','d/datenmaske.html',''],
['Datenmodell','d/datenmodell.html',''],
['Datenpaket','d/datenpaket.html',''],
['Datenreduktion','d/datenreduktion.html',''],
['Datenrettung','d/datenrettung.html',''],
['Datensatz','d/datensatz.html',''],
['Datenschutz','d/datenschutz.html',''],
['Datensicherheit','d/datensicherheit.html',''],
['Datensicherung','d/datensicherung.html',''],
['Datensicherungsprogramm','d/datensicherungsprogramm.html',''],
['Datenträger','d/datentraeger.html',''],
['Datenträgername','d/datentraegername.html',''],
['Datentyp','d/datentyp.html',''],
['Datentyptransformation','d/datentyptransformation.html',''],
['Datentypverletzung','d/datentypverletzung.html',''],
['Datenübertragung','d/datenuebertragung.html',''],
['Datenverarbeitung','d/datenverarbeitung.html',''],
['Datenverlust','d/datenverlust.html',''],
['Datenverschlüsselung','d/datenverschluesselung.html',''],
['Datenverwaltungsprogramm','d/datenverwaltungsprogramm.html',''],
['Datenwort','d/datenwort.html',''],
['DATEV','d/datev.html',''],
['DB2','d/db2.html',''],
['dBase','d/dbase.html',''],
['DBF','d/dbf.html',''],
['DCA','d/dca.html',''],
['DCE','d/dce.html',''],
['DCI','d/dci.html',''],
['DDE','d/dde.html',''],
['DDR2-RAM','d/ddr2-ram.html',''],
['DDR-SDRAM','d/ddr-sdram.html',''],
['Dead Key','d/dead-key.html',''],
['Debuggen','d/debuggen.html',''],
['Debugger','d/debugger.html',''],
['Dedicated Server','d/dedicated-server.html',''],
['Deklaration','d/deklaration.html',''],
['Dekomprimieren','d/dekomprimieren.html',''],
['Dekrementieren','d/dekrementieren.html',''],
['Delimiter','d/delimiter.html',''],
['Deltaröhre','d/deltaroehre.html',''],
['Denial of Service','d/denial-of-service.html',''],
['Designer','d/designer.html',''],
['Desk Accessories','d/desk-accessories.html',''],
['Desktop','d/desktop.html',''],
['Desktop-Betriebssystem','d/desktop-betriebssystem.html',''],
['Desktop-PC','d/desktop-pc.html',''],
['Destruktives Lesen','d/destruktives-lesen.html',''],
['Dezentrale Datenverarbeitung','d/dezentrale-datenverarbeitung.html',''],
['Dezimalkomma','d/dezimalkomma.html',''],
['Dezimalsystem','d/dezimalsystem.html',''],
['DFÜ','d/dfue.html',''],
['Dhrystone','d/dhrystones.html',''],
['Diagramm','d/diagramm.html',''],
['Dialekt','d/dialekt.html',''],
['Dialer','d/dialer.html',''],
['Dialogbox','d/dialogbox.html',''],
['Digital','d/digital.html',''],
['Digital-Analog-Wandler','d/digital-analog-wandler.html',''],
['Digitalisieren','d/digitalisieren.html',''],
['Digitalkamera','d/digitalkamera.html',''],
['Digitizer','d/digitizer.html',''],
['DIN','d/din.html',''],
['Diode','d/diode.html',''],
['DIP-Gehäuse','d/dip-gehaeuse.html',''],
['DIP-Schalter','d/dip-schalter.html',''],
['Directory','d/directory.html',''],
['DirectX','d/directx.html',''],
['Direktzugriffsspeicher','d/direktzugriffsspeicher.html',''],
['Dirty Digital','d/dirty-digital.html',''],
['Disassembler','d/disassembler.html',''],
['Disassemblieren','d/disassemblieren.html',''],
['Diskdoktor','d/diskdoktor.html',''],
['Diskette','d/diskette.html',''],
['Diskettenlaufwerk','d/diskettenlaufwerk.html',''],
['DISOSS','d/disoss.html',''],
['Display','d/display.html',''],
['Dithering','d/dithering.html',''],
['Divide and Conquer-Verfahren','d/divide-and-conquer-verfahren.html',''],
['Division durch Null','d/division-durch-null.html',''],
['DiVX','d/divx.html',''],
['DLL','d/dll.html',''],
['DMA','d/dma.html',''],
['Docking-Station','d/docking-station.html',''],
['Dokument','d/dokument.html',''],
['Dongle','d/dongle.html',''],
['DOS','d/dos.html',''],
['DOS-Eingabeaufforderung','d/dos-eingabeaufforderung.html',''],
['DOS-Kompatibilitätsmodus','d/dos-kompatibilitaetsmodus.html',''],
['DOS-Umgebungsbereich','d/dos-umgebungsbereich.html',''],
['DOS-Umgebungsvariable','d/dos-umgebungsvariable.html',''],
['Dotierung','d/dotierung.html',''],
['Double Buffering','d/double-buffering.html',''],
['Download','d/download.html',''],
['Downsizing','d/downsizing.html',''],
['Dpi','d/dpi.html',''],
['DPMI','d/dpmi.html',''],
['DQDB','d/dqdb.html',''],
['Draft-Modus','d/draft-modus.html',''],
['Drahtmodell','d/drahtmodell.html',''],
['DRAM','d/dram.html',''],
['Dreierkonferenz','d/dreierkonferenz.html',''],
['Dreifachklick','d/dreifachklick.html',''],
['Drittanbieter','d/drittanbieter.html',''],
['Drivespace','d/drivespace.html',''],
['Druckdatei','d/druckdatei.html',''],
['Drucker','d/drucker.html',''],
['Druckerpatrone','d/druckerpatrone.html',''],
['Druckerpuffer','d/druckerpuffer.html',''],
['Druckertreiber','d/druckertreiber.html',''],
['Druckformatspalte','d/druckformatspalte.html',''],
['Druckformatvorlage','d/druckformatvorlage.html',''],
['Druckgeschwindigkeit','d/druckgeschwindigkeit.html',''],
['Druckkopf','d/druckkopf.html',''],
['Druckmanager','d/druckmanager.html',''],
['Druck-Server','d/druck-server.html',''],
['DRV-Format','d/drv-format.html',''],
['DRW-Format','d/drw-format.html',''],
['DSL','d/dsl.html',''],
['DTE','d/dte.html',''],
['DTP','d/dtp.html',''],
['DTP-Programm','d/dtp-programm.html',''],
['DTR','d/dtr.html',''],
['Dual Core Prozessor','d/dual-core-prozessor.html',''],
['Dump','d/dump.html',''],
['Duplex','d/duplex.html',''],
['Durchschuss','d/durchschuss.html',''],
['DV','d/dv.html',''],
['DVD','d/dvd.html',''],
['DVD-Brenner','d/dvd-brenner.html',''],
['DVD-Laufwerk','d/dvd-laufwerk.html',''],
['DVI','d/dvi.html',''],
['DX','d/dx.html',''],
['DX2','d/dx2.html',''],
['DX4','d/dx4.html',''],
['DXF-Format','d/dxf-format.html',''],
['Dyadisch','d/dyadisch.html',''],
['Dynamische Arrays','d/dynamische-arrays.html',''],
['Dynamische Bindung','d/dynamische-bindung.html',''],
['Dynamisches Routing','d/dynamisches-routing.html',''],
['E/A','e/e-a.html',''],
['E-Business','e/e-business.html',''],
['E-Cash','e/e-cash.html',''],
['E-Commerce','e/e-commerce.html',''],
['E-Learning','e/e-learning.html',''],
['E-Mail','e/e-mail.html',''],
['E-Mail-Filter','e/e-mail-filter.html',''],
['E-Mail-Marketing','e/e-mail-marketing.html',''],
['EAN-Code','e/ean-code.html',''],
['EAZ','e/eaz.html',''],
['EBCDIC','e/ebcdic.html',''],
['Ebene','e/ebene.html',''],
['EBit','e/ebit.html',''],
['EByte','e/ebyte.html',''],
['Echtfarbendarstellung','e/echtfarbendarstellung.html',''],
['Echtzeituhr','e/echtzeituhr.html',''],
['Echtzeitverarbeitung','e/echtzeitverarbeitung.html',''],
['ECM','e/ecm.html',''],
['EDIT','e/edit.html',''],
['Editieren','e/editieren.html',''],
['Editor','e/editor.html',''],
['EDLIN','e/edlin.html',''],
['EDO','e/edo.html',''],
['EDO-RAM','e/edo-ram.html',''],
['EDO-VRAM','e/edo-vram.html',''],
['EDRAM','e/edram.html',''],
['Edutainment','e/edutainment.html',''],
['EDV','e/edv.html',''],
['EEPROM','e/eeprom.html',''],
['EGA','e/ega.html',''],
['EIDE','e/eide.html',''],
['Eiffel','e/eiffel.html',''],
['Einfügemodus','e/einfuegemodus.html',''],
['Eingabe/Ausgabe','e/eingabe-ausgabe.html',''],
['Eingabegerät','e/eingabegeraet.html',''],
['EISA-Bus','e/eisa-bus.html',''],
['ELAN','e/elan.html',''],
['Electronic Publishing','e/electronic-publishing.html',''],
['Elektrisches Feld','e/elektrisches-feld.html',''],
['Elektrolumineszenz-Bildschirm','e/elektrolumineszenz-bildschirm.html',''],
['Elektromagnetisches Wechselfeld','e/elektromagnetisches-wechselfeld.html',''],
['Elektrostatik','e/elektrostatik.html',''],
['Elektrostatisches Feld','e/elektrostatisches-feld.html',''],
['El-Torito-Spezifikation','e/el-torito-spezifikation.html',''],
['EMACS','e/emacs.html',''],
['E-Mail-Postfach','e/e-mail-postfach.html',''],
['Em Dash','e/em-dash.html',''],
['EMM.EXE','e/emm-exe.html',''],
['Emoticon','e/emoticon.html',''],
['EMS-Speicher','e/ems-speicher.html',''],
['Emulator','e/emulator.html',''],
['EMV','e/emv.html',''],
['Encarta','e/encarta.html',''],
['En Dash','e/en-dash.html',''],
['Endbenutzer Lizenzvertrag','e/endbenutzer-lizenzvertrag.html',''],
['Endlospapier','e/endlospapier.html',''],
['Endlosschleife','e/endlosschleife.html',''],
['Endnote','e/endnote.html',''],
['Energiesparmaßnahmen','e/energiesparmassnahmen.html',''],
['Energy-Star','e/energy-star.html',''],
['Engine','e/engine.html',''],
['Enhanced IDE','e/enhanced-ide.html',''],
['Eniac','e/eniac.html',''],
['Entity-Relationship-Modell','e/entity-relationship-modell.html',''],
['Entspiegelung','e/entspiegelung.html',''],
['Entwicklunssystem','e/entwicklungssystem.html',''],
['EPP','e/epp.html',''],
['EPROM','e/eprom.html',''],
['EPROM-Brenner','e/eprom-brenner.html',''],
['EPS','e/eps.html',''],
['Epson','e/epson.html',''],
['EPT','e/ept.html',''],
['Ergonomie','e/ergonomie.html',''],
['Erweiterung','e/erweiterung.html',''],
['ESC','e/esc.html',''],
['ESCD','e/escd.html',''],
['Ethernet','e/ethernet.html',''],
['Ethertalk','e/ethertalk.html',''],
['Eumel','e/eumel.html',''],
['EVA-Prinzip','e/eva-prinzip.html',''],
['Exa','e/exa.html',''],
['Excel','e/excel.html',''],
['Exclusive Or','e/exclusive-or.html',''],
['Executive','e/executive.html',''],
['EXE-Format','e/exe-format.html',''],
['Expanded Memory Manager','e/expanded-memory-manager.html',''],
['Expertensystem','e/expertensystem.html',''],
['Expireware','e/expireware.html',''],
['Explorer','e/explorer.html',''],
['Exponent','e/exponent.html',''],
['Export','e/export.html',''],
['Extended Memory Manager','e/extended-memory-manager.html',''],
['Externer Befehl','e/externer-befehl.html',''],
['Externer Rechner','e/externer-rechner.html',''],
['Extranet','e/extranet.html',''],
['Extrusion','e/extrusion.html',''],
['Exzeß--Code','e/exzess--code.html',''],
['Eye-Tracker','e/eye-tracker.html',''],
['F-Codierung','f/f-codierung.html',''],
['Fadenkreuz','f/fadenkreuz.html',''],
['Fakturierungsprogramm','f/fakturierungsprogramm.html',''],
['Fakultät','f/fakultaet.html',''],
['Fallback','f/fallback.html',''],
['Fallunterscheidung','f/fallunterscheidung.html',''],
['Fanfold','f/fanfold.html',''],
['FAQ','f/faq.html',''],
['Farbband','f/farbband.html',''],
['Farbmanagementsystem','f/farbmanagementsystem.html',''],
['Farbmischung','f/farbmischung.html',''],
['Farbmodell','f/farbmodell.html',''],
['Farbpalette','f/farbpalette.html',''],
['Farbreduktion','f/farbreduktion.html',''],
['Farbrolle','f/farbrolle.html',''],
['Farbseparation','f/farbseparation.html',''],
['Farbspektrum','f/farbspektrum.html',''],
['Farbsublimationsdrucker','f/farbsublimationsdrucker.html',''],
['Farbtiefe','f/farbtiefe.html',''],
['Fastpath','f/fastpath.html',''],
['FAX','f/fax.html',''],
['FDDI','f/fddi.html',''],
['Feature','f/feature.html',''],
['Fehlerbehandlungsroutine','f/fehlerbehandlungsroutine.html',''],
['Fehlertoleranz','f/fehlertoleranz.html',''],
['Fenster','f/fenster.html',''],
['Festplatte','f/festplatte.html',''],
['FIF-Format','f/fif-format.html',''],
['FIFO','f/fifo.html',''],
['File-Locking','f/file-locking.html',''],
['File-Server','f/file-server.html',''],
['File-Sharing','f/file-sharing.html',''],
['Film','f/film.html',''],
['Filter','f/filter.html',''],
['Filtering','f/filtering.html',''],
['Finanzbuchhaltung','f/finanzbuchhaltung.html',''],
['Finder','f/finder.html',''],
['Finitheit','f/finitheit.html',''],
['Firewall','f/firewall.html',''],
['FireWire','f/firewire.html',''],
['Firmware','f/firmware.html',''],
['First in, first out','f/first-in-first-out.html',''],
['First-Level-Cache','f/first-level-cache.html',''],
['FKS','f/fks.html',''],
['Flächendiagramm','f/flaechendiagramm.html',''],
['Flachbett-Scanner','f/flachbett-scanner.html',''],
['Flag','f/flag.html',''],
['Flame','f/flame.html',''],
['Flash-Memory','f/flash-memory.html',''],
['Flatrate','f/flatrate.html',''],
['Flat-Shading','f/flat-shading.html',''],
['Flatterrand','f/flatterrand.html',''],
['Fließkomma-Variable','f/fliesskomma-variable.html',''],
['Fließtext','f/fliesstext.html',''],
['Flimmern','f/flimmern.html',''],
['Flipflop','f/flipflop.html',''],
['FLOPS','f/flops.html',''],
['Flußsteuerung','f/flusssteuerung.html',''],
['Flußwechsel','f/flusswechsel.html',''],
['Fly-out-Menü','f/fly-out-menue.html',''],
['Focus','f/focus.html',''],
['Fogging','f/fogging.html',''],
['Fokussierer','f/fokussierer.html',''],
['Folder','f/folder.html',''],
['Folientastatur','f/folientastatur.html',''],
['Font','f/font.html',''],
['Font/DA-Mover','f/font-da-mover.html',''],
['Font-Manager','f/font-manager.html',''],
['Formatieren','f/formatieren.html',''],
['Formelsatz','f/formelsatz.html',''],
['Formularmodus','f/formularmodus.html',''],
['Form-Virus','f/form-virus.html',''],
['For-Schleife','f/for-schleife.html',''],
['Forth','f/forth.html',''],
['Fortran','f/fortran.html',''],
['FoxPro','f/foxpro.html',''],
['FPP','f/fpp.html',''],
['Fragezeichen','f/fragezeichen.html',''],
['Fragmentiert','f/fragmentiert.html',''],
['Fragmentierung','f/fragmentierung.html',''],
['Fraktal','f/fraktal.html',''],
['Fraktale Bildkompression','f/fraktale-bildkompression.html',''],
['Fraktale Bildkomprimierung','f/fraktale-bildkomprimierung.html',''],
['FRAM','f/fram.html',''],
['Frame','f/frame.html',''],
['Frame Grabber','f/frame-grabber.html',''],
['FrameMaker','f/framemaker.html',''],
['Framework','f/framework.html',''],
['Framing Bits','f/framing-bits.html',''],
['Freak','f/freak.html',''],
['FRED','f/fred.html',''],
['Freeware','f/freeware.html',''],
['Freihandschere','f/freihandschere.html',''],
['Freihandzeichnen','f/freihandzeichnen.html',''],
['Frequenz','f/frequenz.html',''],
['Frequenzmultiplex-Verfahren','f/frequenzmultiplex-verfahren.html',''],
['Frequenzwahlverfahren','f/frequenzwahlverfahren.html',''],
['Friktionsantrieb','f/friktionsantrieb.html',''],
['Frontware','f/frontware.html',''],
['FSB','f/fsb.html',''],
['FST-LCD','f/fst-lcd.html',''],
['FTP','f/ftp.html',''],
['Fujitsu','f/fujitsu.html',''],
['Fully populated','f/fully-populated.html',''],
['Funktion','f/funktion.html',''],
['Funktionsplotter','f/funktionsplotter.html',''],
['Funktionstaste','f/funktionstaste.html',''],
['Fußgesteuerte Schleife','f/fussgesteuerte-schleife.html',''],
['Fußnote','f/fussnote.html',''],
['Fußzeile','f/fusszeile.html',''],
['Fuzzing','f/fuzzing.html',''],
['Fuzzy-Logik','f/fuzzy-logik.html',''],
['Gameport','g/gameport.html',''],
['GAN','g/gan.html',''],
['Ganzseitenbildschirm','g/ganzseitenbildschirm.html',''],
['Ganzseiteneditor','g/ganzseiteneditor.html',''],
['Ganzzahl','g/ganzzahl.html',''],
['Garbage Collection','g/garbage-collection.html',''],
['Gastzugang','g/gastzugang.html',''],
['Gateway','g/gateway.html',''],
['Gatter','g/gatter.html',''],
['GBit','g/gbit.html',''],
['GByte','g/gbyte.html',''],
['GDDR-Speicher','g/gddr-speicher.html',''],
['GDI','g/gdi.html',''],
['GDI-Drucker','g/gdi-drucker.html',''],
['Gebrochener Wert','g/gebrochener-wert.html',''],
['Gebührenanzeige','g/gebuehrenanzeige.html',''],
['GEL','g/gel.html',''],
['GEM','g/gem.html',''],
['Gemischter Bezug','g/gemischter-bezug.html',''],
['General Problem Solver','g/general-problem-solver.html',''],
['Generisch','g/generisch.html',''],
['Genlock-Karte','g/genlock-karte.html',''],
['GEOS','g/geos.html',''],
['Geräte-Manager','g/geraete-manager.html',''],
['Gerätetreiber','g/geraetetreiber.html',''],
['Gesamt-Backup','g/gesamt-backup.html',''],
['Geschäftsgrafik','g/geschaeftsgrafik.html',''],
['Geschäftsgrafikprogramm','g/geschaeftsgrafikprogramm.html',''],
['Geschicklichkeitsspiel','g/geschicklichkeitsspiel.html',''],
['Geschlossene Benutzergruppe','g/geschlossene-benutzergruppe.html',''],
['Geschützter Trennstrich','g/geschuetzter-trennstrich.html',''],
['Geschütztes Leerzeichen','g/geschuetztes-leerzeichen.html',''],
['Gesture','g/gesture.html',''],
['Geviert','g/geviert.html',''],
['Ghost Icon','g/ghost-icon.html',''],
['GHz','g/ghz.html',''],
['GIF','g/gif.html',''],
['Giga','g/giga.html',''],
['GIGO','g/gigo.html',''],
['GIS','g/gis.html',''],
['Gitter','g/gitter.html',''],
['Globale Variable','g/globale-variable.html',''],
['Globalisierung','g/globalisierung.html',''],
['Global Naming','g/global-naming.html',''],
['GLSI','g/glsi.html',''],
['Gopher','g/gopher.html',''],
['Goto','g/goto.html',''],
['Gouraud-Shading','g/gouraud-shading.html',''],
['GPRS','g/gprs.html',''],
['GPS','g/gps.html',''],
['Grafik','g/grafik.html',''],
['Grafikbibliothek','g/grafikbibliothek.html',''],
['Grafikformat','g/grafikformat.html',''],
['Grafikkarte','g/grafikkarte.html',''],
['Grafikmodus','g/grafikmodus.html',''],
['Grafikprogramm','g/grafikprogramm.html',''],
['Grafikprozessor','g/grafikprozessor.html',''],
['Grafikstandard','g/grafikstandard.html',''],
['Grafiktablett','g/grafiktablett.html',''],
['Grafische Primitive','g/grafische-primitive.html',''],
['Green Monitor Adapter','g/green-monitor-adapter.html',''],
['Großbildschirm','g/grossbildschirm.html',''],
['Großrechner','g/grossrechner.html',''],
['Großvater-Vater-Sohn Prinzip','g/grossvater-vater-sohn-prinzip.html',''],
['Grotesk','g/grotesk.html',''],
['Groupware','g/groupware.html',''],
['Groupwise','g/groupwise.html',''],
['GSM','g/gsm.html',''],
['Gummiband','g/gummiband.html',''],
['Hack','h/hack.html',''],
['Hacker','h/hacker.html',''],
['Halbbyte','h/halbbyte.html',''],
['Halbduplex','h/halbduplex.html',''],
['Halbfett','h/halbfett.html',''],
['Halbleiter','h/halbleiter.html',''],
['Halbtonbild','h/halbtonbild.html',''],
['Half Track','h/half-track.html',''],
['Ham','h/ham.html',''],
['Handbuch','h/handbuch.html',''],
['Handheld','h/handheld.html',''],
['Handlungsreisenden Problem','h/handlungsreisenden-problem.html',''],
['Hand-Scanner','h/hand-scanner.html',''],
['Handshake','h/handshake.html',''],
['Hang-up','h/hang-up.html',''],
['Hardcopy','h/hardcopy.html',''],
['Hardcopy-Programm','h/hardcopy-programm.html',''],
['Hardsektorierung','h/hardsektorierung.html',''],
['Hardware','h/hardware.html',''],
['Hardware-Interrupt','h/hardware-interrupt.html',''],
['Harter Return','h/harter-return.html',''],
['Harvard Graphics','h/harvard-graphics.html',''],
['Hauptplatine','h/hauptplatine.html',''],
['Hauptschleife','h/hauptschleife.html',''],
['Hayes','h/hayes.html',''],
['HDLC','h/hdlc.html',''],
['HD Ready','h/hd-ready.html',''],
['HDTV','h/hdtv.html',''],
['Head-Tracker','h/head-tracker.html',''],
['Headcrash','h/headcrash.html',''],
['Header','h/header.html',''],
['Header-Datei','h/header-datei.html',''],
['Headset','h/headset.html',''],
['Heapsort','h/heapsort.html',''],
['Heatpipe','h/heatpipe.html',''],
['Heimcomputer','h/heimcomputer.html',''],
['Heisenbug','h/heisenbug.html',''],
['Hello, world!','h/hello-world.html',''],
['Help-Compiler','h/help-compiler.html',''],
['Helvetica','h/helvetica.html',''],
['Hertz','h/hertz.html',''],
['Heterogenes Netzwerk','h/heterogenes-netzwerk.html',''],
['Hewlett Packard','h/hewlett-packard.html',''],
['Hexadezimalsystem','h/hexadezimalsystem.html',''],
['Hexdump','h/hexdump.html',''],
['HF-Modulator','h/hf-modulator.html',''],
['Hidden','h/hidden.html',''],
['Hierarchische Datenbank','h/hierarchische-datenbank.html',''],
['Hierarchisches Dateisystem','h/hierarchisches-dateisystem.html',''],
['High Color','h/high-color.html',''],
['High-End','h/high-end.html',''],
['High-Memory-Area','h/high-memory-area.html',''],
['High-Speed-Modem','h/high-speed-modem.html',''],
['Hijaker','h/hijacker.html',''],
['Hilfefunktion','h/hilfefunktion.html',''],
['Hilfsprogramm','h/hilfsprogramm.html',''],
['HIMEM.SYS','h/himem-sys.html',''],
['Hintergrundprozeß','h/hintergrundprozess.html',''],
['Hires','h/hires.html',''],
['HKEY','h/hkey.html',''],
['Hoher Speicherbereich','h/hoher-speicherbereich.html',''],
['Home Banking','h/home-banking.html',''],
['Home Shopping','h/home-shopping.html',''],
['Horizontalfrequenz','h/horizontalfrequenz.html',''],
['Host','h/host.html',''],
['Host-Adapter','h/host-adapter.html',''],
['Hot Corner','h/hot-corner.html',''],
['Hot Fix','h/hot-fix.html',''],
['Hotkey','h/hotkey.html',''],
['Hotline','h/hotline.html',''],
['HPFS','h/hpfs.html',''],
['HPGL','h/hpgl.html',''],
['HSB','h/hsb.html',''],
['HTML','h/html.html',''],
['Hub','h/hub.html',''],
['Hybridsprache','h/hybridsprache.html',''],
['Hypercard','h/hypercard.html',''],
['Hyperlink','h/hyperlink.html',''],
['Hypershow','h/hypershow.html',''],
['Hypertext','h/hypertext.html',''],
['Hyper-Threading','h/hyper-threading.html',''],
['Hyperware','h/hyperware.html',''],
['Hz','h/hz.html',''],
['I','i/i-symbol.html',''],
['IBM','i/ibm.html',''],
['IBM-kompatibler PC','i/ibm-kompatibler-pc.html',''],
['IBM-PC','i/ibm-pc.html',''],
['IBM-PC/AT','i/ibm-pc-at.html',''],
['IBM-PC, funktionsweise Aufbau','i/ibm-pc-funktionsweise-aufbau.html',''],
['Icon','i/icon.html',''],
['Icon-Editor','i/icon-editor.html',''],
['ID','i/id.html',''],
['IDAPI','i/idapi.html',''],
['Identifikations-Byte','i/identifikations-byte.html',''],
['IEEE','i/ieee.html',''],
['IFF','i/iff.html',''],
['If...Then...Else','i/if-then-else.html',''],
['Illegal Opcode','i/illegal-opcode.html',''],
['Illustrationsprogramm','i/illustrationsprogramm.html',''],
['Image-Backup','i/image-backup.html',''],
['Image-Header','i/image-header.html','iMode','i/imode.html',''],
['Imperative Programmierung','i/imperative-programmierung.html',''],
['Implikation','i/implikation.html',''],
['Import','i/import.html',''],
['Indeo','i/indeo.html',''],
['Index','i/index.html',''],
['Indexregister','i/indexregister.html',''],
['Indexsequentielle Datenbank','i/indexsequentielle-datenbank.html',''],
['Infixnotation','i/infixnotation.html',''],
['Informatik','i/informatik.html',''],
['Information Highway','i/information-highway.html',''],
['Infotainment','i/infotainment.html',''],
['Inhaltsverzeichnis','i/inhaltsverzeichnis.html',''],
['INI','i/ini.html',''],
['Init','i/init.html',''],
['Initial','i/initial.html',''],
['Initialisierungsdatei','i/initialisierungsdatei.html',''],
['Inkremental-Compiler','i/inkremental-compiler.html',''],
['Inkrementieren','i/inkrementieren.html',''],
['Installation','i/installation.html',''],
['Installationsprogramm','i/installationsprogramm.html',''],
['Instanz','i/instanz.html',''],
['Integer-Variable','i/integer-variable.html',''],
['Integrationstest','i/integrationstest.html',''],
['Integr. Entwicklungsumgebung','i/integrierte-entwicklungsumgebung.html',''],
['Integriertes Software Paket','i/integriertes-software-paket.html',''],
['Intel','i/intel.html',''],
['Interaktiv','i/interaktiv.html',''],
['Interface','i/interface.html',''],
['Interlace','i/interlace.html',''],
['Internationalisierung','i/internationalisierung.html',''],
['Interner Befehl','i/interner-befehl.html',''],
['Internet','i/internet.html',''],
['Internet by Call','i/internet-by-call.html',''],
['Internet-Marketing','i/internet-marketing.html',''],
['Internet-Protokoll','i/internet-protokoll.html',''],
['Interpreter','i/interpreter.html',''],
['Interrupt','i/interrupt.html',''],
['Intranet','i/intranet.html',''],
['IPC','i/ipc.html',''],
['IPP','i/ipp.html',''],
['Ips','i/ips.html',''],
['IPX','i/ipx.html',''],
['IPX/SPX','i/ipx-spx.html',''],
['IrDA','i/irda.html',''],
['IRQ','i/irq.html',''],
['ISAM','i/isam.html',''],
['ISDN','i/isdn.html',''],
['ISO','i/iso.html',''],
['IT','i/it.html','iTAN','i/itan.html',''],
['Itanium','i/itanium.html',''],
['Itanium ','i/itanium-.html',''],
['Iteration','i/iteration.html',''],
['ITU','i/itu.html',''],
['Jam','j/jam.html',''],
['Java-Applet','j/java-applet.html',''],
['JAZ-Laufwerk','j/jaz-laufwerk.html',''],
['Jitter','j/jitter.html',''],
['Jock','j/jock.html',''],
['Jokerzeichen','j/jokerzeichen.html',''],
['JOVIAL','j/jovial.html',''],
['Joystick','j/joystick.html',''],
['JPEG','j/jpeg.html',''],
['JPEG++','j/jpeg-plus-plus.html',''],
['Jumper','j/jumper.html',''],
['Kalibrierung','k/kalibrierung.html',''],
['Kaltstart','k/kaltstart.html',''],
['Kanalbündelung','k/kanalbuendelung.html',''],
['Kapitälchen','k/kapitaelchen.html',''],
['Kapselung','k/kapselung.html',''],
['Kardinalzahl','k/kardinalzahl.html',''],
['Kassette','k/kassette.html',''],
['Kenbak-','k/kenbak-.html',''],
['Kermit','k/kermit.html',''],
['Kernel','k/kernel.html',''],
['Key Disk','k/key-disk.html',''],
['KI','k/ki.html',''],
['Klammeraffe','k/klammeraffe.html',''],
['Klartext','k/klartext.html',''],
['Klasse','k/klasse.html',''],
['Klick','k/klick.html',''],
['Knacken','k/knacken.html',''],
['Knoten','k/knoten.html',''],
['Knowledge Engineering','k/knowledge-engineering.html',''],
['Koaxialkabel','k/koaxialkabel.html',''],
['Komfortanschluss','k/komfortanschluss.html',''],
['Kommandoorientiert','k/kommandoorientiert.html',''],
['Kommentar','k/kommentar.html',''],
['Kommunikation','k/kommunikation.html',''],
['Kommunikationspartner','k/kommunikationspartner.html',''],
['Kommunikationsprogramm','k/kommunikationsprogramm.html',''],
['Kompatibel','k/kompatibel.html',''],
['Komplement','k/komplement.html',''],
['Komplementärcode','k/komplementaercode.html',''],
['Kompletter Bypass','k/kompletter-bypass.html',''],
['Komplettsysteme','k/komplettsysteme.html',''],
['Komprimieren','k/komprimieren.html',''],
['Konferenz','k/konferenz.html',''],
['Konfigurationsbefehl','k/konfigurationsbefehl.html',''],
['Konfigurationsdatenbank','k/konfigurationsdatenbank.html',''],
['Konflikt','k/konflikt.html',''],
['Konsole','k/konsole.html',''],
['Konstante','k/konstante.html',''],
['Kontextmenü','k/kontextmenue.html',''],
['Kontrollstruktur','k/kontrollstruktur.html',''],
['Konventioneller Arbeitsspeicher','k/konventioneller-arbeitsspeicher.html',''],
['Konvergenz','k/konvergenz.html',''],
['Konvertierung','k/konvertierung.html',''],
['Konvertierungsprogramm','k/konvertierungsprogramm.html',''],
['Kopierprogramm','k/kopierprogramm.html',''],
['Kopierschutz','k/kopierschutz.html',''],
['Kreisdiagramm','k/kreisdiagramm.html',''],
['K&R-Sprachumfang','k/k-r-sprachumfang.html',''],
['Kryptoanalyse','k/kryptoanalyse.html',''],
['Kühler','k/kuehler.html',''],
['Künstliches Leben','k/kuenstliches-leben.html',''],
['Kugelkopf','k/kugelkopf.html',''],
['Kurvendiagramm','k/kurvendiagramm.html',''],
['Kybernetik','k/kybernetik.html',''],
['Label','l/label.html',''],
['Laden','l/laden.html',''],
['Landscape','l/landscape.html',''],
['LAN Manager','l/lan-manager.html',''],
['LAN Server','l/lan-server.html',''],
['LAP-M','l/lap-m.html',''],
['Laptop','l/laptop.html',''],
['Laser','l/laser.html',''],
['Laserdrucker','l/laserdrucker.html',''],
['Latenz','l/latenz.html',''],
['Laufwerk','l/laufwerk.html',''],
['Laufzeitfehler','l/laufzeitfehler.html',''],
['Layer','l/layer.html',''],
['LBA','l/lba.html',''],
['LCD','l/lcd.html',''],
['LED','l/led.html',''],
['LED-Drucker','l/led-drucker.html',''],
['Leer-String','l/leer-string.html',''],
['Lernprogramm','l/lernprogramm.html',''],
['Level','l/level.html',''],
['LEX','l/lex.html',''],
['LGA-CPU-Sockel','l/lga-cpu-sockel.html',''],
['LHA','l/lha.html',''],
['Lichtwellenleiter','l/lichtwellenleiter.html',''],
['Lies-mich-Datei','l/lies-mich-datei.html',''],
['LIFO','l/lifo.html',''],
['Lightpen','l/lightpen.html',''],
['LIM-EMS','l/lim-ems.html',''],
['Limulator','l/limulator.html',''],
['Lineal','l/lineal.html',''],
['Liniendiagramm','l/liniendiagramm.html',''],
['Linker','l/linker.html',''],
['Linksbündig','l/linksbuendig.html',''],
['Link-Virus','l/link-virus.html',''],
['Linkzeit','l/linkzeit.html',''],
['Linux','l/linux.html',''],
['Lisp','l/lisp.html',''],
['List-Programm','l/list-programm.html',''],
['List-Schutz','l/list-schutz.html',''],
['Little-Endian','l/little-endian.html',''],
['Live-and-die-Virus','l/live-and-die-virus.html',''],
['Lochabstand','l/lochabstand.html',''],
['Lochkarte','l/lochkarte.html',''],
['Logarithmus','l/logarithmus.html',''],
['Logik','l/logik.html',''],
['Login','l/login.html',''],
['Login-Script','l/login-script.html',''],
['Logisches Laufwerke','l/logisches-laufwerk.html',''],
['Lokaler Bypass','l/lokaler-bypass.html',''],
['Lokales Netzwerk','l/lokales-netzwerk.html',''],
['Lokalisierung','l/lokalisierung.html',''],
['Longitudinal-Recording','l/longitudinal-recording-technik.html',''],
['Lotus','l/lotus.html',''],
['Low-End','l/low-end.html',''],
['Low-Level-Format','l/low-level-format.html',''],
['LPT:','l/lpt.html',''],
['LSI','l/lsi.html',''],
['LZW','l/lzw.html',''],
['Mach','m/mach.html',''],
['Macintosh','m/macintosh.html',''],
['Macintosh-Oberfläche','m/macintosh-oberflaeche.html',''],
['MacOS','m/macos.html',''],
['Macromind Director','m/macromind-director.html',''],
['Macrovision','m/macrovision.html',''],
['Magnetband','m/magnetband.html',''],
['Magnetblasenspeicher','m/magnetblasenspeicher.html',''],
['Magnetkernspeicher','m/magnetkernspeicher.html',''],
['Mail-Merge','m/mail-merge.html',''],
['Main()','m/main.html',''],
['Mainboard','m/mainboard.html',''],
['Makeln','m/makeln.html',''],
['Makro','m/makro.html',''],
['Makro-Assembler','m/makro-assembler.html',''],
['Makrorekorder','m/makrorekorder.html',''],
['Makrosprache','m/makrosprache.html',''],
['Makrovirus','m/makrovirus.html',''],
['Malprogramm','m/malprogramm.html',''],
['Maltron-Tastatur','m/maltron-tastatur.html',''],
['MAN','m/man.html',''],
['Mandelbug','m/mandelbug.html',''],
['MAP','m/map.html',''],
['MAPI','m/mapi.html',''],
['Mapping','m/mapping.html',''],
['Marketing','m/marketing.html',''],
['Markieren','m/markieren.html',''],
['Maschennetz-Topologie','m/maschennetz-topologie.html',''],
['Maschinencode','m/maschinencode.html',''],
['Maschinennah','m/maschinennah.html',''],
['Maschinensprache','m/maschinensprache.html',''],
['Maskengenerator','m/maskengenerator.html',''],
['Massenspeicher','m/massenspeicher.html',''],
['Master Boot Record','m/master-boot-record.html',''],
['Matrixdrucker','m/matrixdrucker.html',''],
['MAU','m/mau.html',''],
['Maus','m/maus.html',''],
['MBit','m/mbit.html',''],
['MBit/s','m/mbit-s.html',''],
['MByte','m/mbyte.html',''],
['Mehrbenutzersystem','m/mehrbenutzersystem.html',''],
['Mehrfrequenzbildschirm','m/mehrfrequenzbildschirm.html',''],
['Mehrgeräteanschluss','m/mehrgeraeteanschluss.html',''],
['Mehrzweckregister','m/mehrzweckregister.html',''],
['Memo-Feld','m/memo-feld.html',''],
['Menü','m/menue.html',''],
['Metaanweisung','m/metaanweisung.html',''],
['Metal-Shading','m/metal-shading.html',''],
['Methode','m/methode.html',''],
['MFD','m/mfd.html',''],
['MFM','m/mfm.html',''],
['MGA','m/mga.html',''],
['MHS','m/mhs.html',''],
['Microchannel','m/microchannel.html',''],
['Microsoft','m/microsoft.html',''],
['Microspacing','m/microspacing.html',''],
['MIDI','m/midi.html',''],
['Mikrocode','m/mikrocode.html',''],
['Mikroelektronik','m/mikroelektronik.html',''],
['Mikroprogramm','m/mikroprogramm.html',''],
['MIP-Mapping','m/mip-mapping.html',''],
['MIPS','m/mips.html',''],
['MMORPG','m/mmorpg.html',''],
['MMS','m/mms.html',''],
['MMX-Technologie','m/mmx-technologie.html',''],
['Mnemonik','m/mnemonik.html',''],
['Modem','m/modem.html',''],
['MODS','m/mods.html',''],
['Modularisierung','m/modularisierung.html',''],
['Monadisch','m/monadisch.html',''],
['Monochrom','m/monochrom.html',''],
['Mooresches Gesetz','m/mooresches-gesetz.html',''],
['Mousepad','m/mousepad.html',''],
['MP3-Player','m/mp3-player.html',''],
['MSB','m/msb.html',''],
['Multicore-Prozessor','m/multicore-prozessor.html',''],
['Multidimensionale Datenbank','m/multidimensionale-datenbank.html',''],
['Multiplexing','m/multiplexing.html',''],
['Nachleuchtdauer','n/nachleuchtdauer.html',''],
['Nachricht','n/nachricht.html',''],
['Nadeldrucker','n/nadeldrucker.html',''],
['Named Pipe','n/named-pipe.html',''],
['Namensschema','n/namensschema.html',''],
['NAT','n/nat.html',''],
['Natural Keyboard','n/natural-keyboard.html',''],
['NDS','n/nds.html',''],
['NEAT-Chipsatz','n/neat-chipsatz.html',''],
['Nebenläufigkeit','n/nebenlaeufigkeit.html',''],
['NETBEUI','n/netbeui.html',''],
['Netbios','n/netbios.html',''],
['Netburst-Architektur','n/netburst-architektur.html',''],
['Netiquette','n/netiquette.html',''],
['Netzteil','n/netzteil.html',''],
['Netzwerk','n/netzwerk.html',''],
['Netzwerkarchitektur','n/netzwerkarchitektur.html',''],
['Netzwerkbetriebssystem','n/netzwerkbetriebssystem.html',''],
['Netzwerkbus','n/netzwerkbus.html',''],
['Netzwerkdrucker','n/netzwerkdrucker.html',''],
['Netzwerk-Shell','n/netzwerk-shell.html',''],
['Netzwerktopologie','n/netzwerktopologie.html',''],
['Neuronales Netz','n/neuronales-netz.html',''],
['Newbie','n/newbie.html',''],
['NFS','n/nfs.html',''],
['Nibble','n/nibble.html',''],
['Ninety/Ninety Rule','n/ninety-ninety-rule.html',''],
['NLM','n/nlm.html',''],
['NMI','n/nmi.html',''],
['Noint','n/noint.html',''],
['Nomad','n/nomad.html',''],
['Non-dedicated Server','n/non-dedicated-server.html',''],
['NOP','n/nop.html',''],
['Northbridge','n/northbridge.html',''],
['Not','n/not.html',''],
['Notebook','n/notebook.html',''],
['Novell','n/novell.html',''],
['Novell-Netware','n/novell-netware.html',''],
['NTBA','n/ntba.html',''],
['NTFS','n/ntfs.html',''],
['NuBus','n/nubus.html',''],
['NUL','n/null.html',''],
['Nullmodem','n/nullmodem.html',''],
['Numbercruncher','n/numbercruncher.html',''],
['Numerische Werkzeugmaschine','n/numerische-werkzeugmaschine.html',''],
['Nvidia-Geforce','n/nvidia-geforce.html',''],
['NVRAM','n/nvram.html',''],
['Oberlängen','o/oberlaengen.html',''],
['Oberon','o/oberon.html',''],
['Objektcode','o/objektcode.html',''],
['Objektorientiert','o/objektorientiert.html',''],
['Objekt. Benutzeroberfläche','o/objektorientierte-benutzeroberflaeche.html',''],
['Objekt. Datenbank','o/objektorientierte-datenbank.html',''],
['Objekt. Programmierung','o/objektorientierte-programmierung.html',''],
['Objektrelationale Datenbank','o/objektrelationale-datenbank.html',''],
['OCR','o/ocr.html',''],
['ODAPI','o/odapi.html',''],
['ODBC','o/odbc.html',''],
['OEM','o/oem.html',''],
['Off-by-one Error','o/off-by-one-error.html',''],
['Office-Paket','o/office-paket.html',''],
['Offline','o/offline.html',''],
['Offset','o/offset.html',''],
['Oktalsystem','o/oktalsystem.html',''],
['OLE','o/ole.html',''],
['Oneshot-Verfahren','o/oneshot-verfahren.html',''],
['Online','o/online.html',''],
['Online-Arbeitsmarkt','o/online-arbeitsmarkt.html',''],
['Online-Datenbank','o/online-datenbank.html',''],
['Online-Dienst','o/online-dienst.html',''],
['Online-Informationsdienst','o/online-informationsdienst.html',''],
['Online-Marketing','o/online-marketing.html',''],
['Online-Publishing','o/online-publishing.html',''],
['Opcode','o/opcode.html',''],
['OpenLook','o/openlook.html',''],
['Operand','o/operand.html',''],
['Operator','o/operator.html',''],
['Opteron','o/opteron.html',''],
['Optional','o/optional.html',''],
['Optische Mitte','o/optische-mitte.html',''],
['Optische Platte','o/optische-platte.html',''],
['Optischer Computer','o/optischer-computer.html',''],
['Optoelektronik','o/optoelektronik.html',''],
['Or','o/or.html',''],
['Oracle','o/oracle.html',''],
['Ordinal','o/ordinal.html',''],
['Ordner','o/ordner.html',''],
['Ordnungszahl','o/ordnungszahl.html',''],
['Organigramm','o/organigramm.html',''],
['OSF','o/osf.html',''],
['OSI-Referenzmodell','o/osi-referenzmodell.html',''],
['OSI-Schichtenmodell','o/osi-schichtenmodell.html',''],
['Outsourcing','o/outsourcing.html',''],
['Overhead','o/overhead.html',''],
['Overlay-Datei','o/overlay-datei.html',''],
['Overlay-Karte','o/overlay-karte.html',''],
['P','p/p.html',''],
['PP','p/pp.html',''],
['P-Code','p/p-code.html',''],
['PAD','p/pad.html',''],
['Paddle','p/paddle.html',''],
['PageImpressions','p/pageimpressions.html',''],
['PageMaker','p/pagemaker.html',''],
['Paketvermittlung','p/paketvermittlung.html',''],
['PAL','p/pal.html',''],
['Palmtop','p/palmtop.html',''],
['Pantone','p/pantone.html',''],
['Papierkorb','p/papierkorb.html',''],
['Paradox','p/paradox.html',''],
['Parallele Schnittstelle','p/parallele-schnittstelle.html',''],
['Parameter','p/parameter.html',''],
['Parität','p/paritaet.html',''],
['Parken','p/parken.html',''],
['Parser','p/parser.html',''],
['Partial-CAV-Verfahren','p/partial-cav-verfahren.html',''],
['Partition','p/partition.html',''],
['Partitionstabelle','p/partitionstabelle.html',''],
['Pascal','p/pascal.html',''],
['Pass','p/pass.html',''],
['Passive Kühler','p/passive-kuehler.html',''],
['Passiver Bildschirm','p/passiver-bildschirm.html',''],
['Passwort','p/passwort.html',''],
['Paßwort-Aging','p/passwort-aging.html',''],
['Paßwort-Phishing','p/passwort-phishing.html',''],
['Patch','p/patch.html',''],
['PBit','p/pbit.html',''],
['PByte','p/pbyte.html',''],
['PC','p/pc.html',''],
['PC-Card','p/pc-card.html',''],
['PC-DOS','p/pc-dos.html',''],
['PC-Spiele','p/pc-spiele.html',''],
['PCI-Bus','p/pci-bus.html',''],
['PCI-Express','p/pci-express.html',''],
['PCL','p/pcl.html',''],
['PCMCIA','p/pcmcia.html',''],
['PCX-Datei','p/pcx-datei.html',''],
['PCX-Format','p/pcx-format.html',''],
['PDA','p/pda.html',''],
['PDC','p/pdc.html',''],
['PDS','p/pds.html',''],
['Peer-to-Peer Netzwerk','p/peer-to-peer-netzwerk.html',''],
['Pen Ballpoint','p/pen-ballpoint.html',''],
['Pentium M','p/pentium-m.html',''],
['PEP','p/pep.html',''],
['Performance','p/performance.html',''],
['Peripheriegerät','p/peripheriegeraet.html',''],
['Perpendicular-Recording','p/perpendicular-recording-technik.html',''],
['PET','p/pet.html',''],
['Pflichtenheft','p/pflichtenheft.html',''],
['Phong-Shading','p/phong-shading.html',''],
['Photo-CD','p/photo-cd.html',''],
['Photoshop','p/photoshop.html',''],
['Photozelle','p/photozelle.html',''],
['PIC-Format','p/pic-format.html',''],
['PICT','p/pict.html',''],
['Picture','p/picture.html',''],
['Piezoelektrischer Kristall','p/piezoelektrischer-kristall.html',''],
['Pif-Datei','p/pif-datei.html',''],
['PILOT','p/pilot.html',''],
['PIM','p/pim.html',''],
['Pin','p/pin.html',''],
['Pipe','p/pipe.html',''],
['Pipe-Zeichen','p/pipe-zeichen.html',''],
['Pixel','p/pixel.html',''],
['PL/','p/pl-.html',''],
['Plankalkül','p/plankalkuel.html',''],
['Plattenspiegelung','p/plattenspiegelung.html',''],
['Plug-In','p/plug-in.html',''],
['POST-Code','p/post-code.html',''],
['Postrelationale Datenbank','p/postrelationale-datenbank.html',''],
['Powerline-Kommunikation','p/powerline-kommunikation.html',''],
['Prescott','p/prescott.html',''],
['Primärmultiplex-Anschluss','p/primaermultiplex-anschluss.html',''],
['Programmiersprache','p/programmiersprache.html',''],
['Provider','p/provider.html',''],
['PS/-Bus','p/ps--bus.html',''],
['Pulswahlverfahren','p/pulswahlverfahren.html',''],
['QBasic','q/qbasic.html',''],
['QBE','q/qbe.html',''],
['QDOS','q/qdos.html',''],
['QEMM','q/qemm.html',''],
['QFA','q/qfa.html',''],
['QIC','q/qic.html',''],
['Quadbit','q/quadbit.html',''],
['Quadra','q/quadra.html',''],
['Quark XPress','q/quark-xpress.html',''],
['Quattro Pro','q/quattro-pro.html',''],
['Quellcode','q/quellcode.html',''],
['Quellcodekompatibel','q/quellcodekompatibel.html',''],
['Quick B','q/quick-b.html',''],
['QuickBasic','q/quickbasic.html',''],
['QuickDraw','q/quickdraw.html',''],
['Quicken','q/quicken.html',''],
['Quicksort','q/quicksort.html',''],
['QuickTime','q/quicktime.html',''],
['Quote','q/quote.html',''],
['QWERTY-Tastatur','q/qwerty-tastatur.html',''],
['QWERTZ-Tastatur','q/qwertz-tastatur.html',''],
['RBase','r/r-base.html',''],
['Rackware','r/rackware.html',''],
['Radiosity','r/radiosity.html',''],
['RAID','r/raid.html',''],
['RAM','r/ram.html',''],
['RAMDAC','r/ramdac.html',''],
['RAM-Disk','r/ram-disk.html',''],
['Raubkopie','r/raubkopie.html',''],
['Raytracing','r/raytracing.html',''],
['Real Mode','r/real-mode.html',''],
['Real-Variable','r/real-variable.html',''],
['Rechenzentrum','r/rechenzentrum.html',''],
['Rechnerplattform','r/rechnerplattform.html',''],
['Rechtsbündig','r/rechtsbuendig.html',''],
['Rechtschreibprüfer','r/rechtschreibpruefer.html',''],
['Recompiler','r/recompiler.html',''],
['Record-Locking','r/record-locking.html',''],
['Recycling','r/recycling.html',''],
['Redraw','r/redraw.html',''],
['Redundanz','r/redundanz.html',''],
['Reentrant','r/reentrant.html',''],
['Register','r/register.html',''],
['Reinraum','r/reinraum.html',''],
['Rekursion','r/rekursion.html',''],
['Rekursive Dateioperation','r/rekursive-dateioperation.html',''],
['Relationale Datenbank','r/relationale-datenbank.html',''],
['Relativer Bezug','r/relativer-bezug.html',''],
['Relokatibel','r/relokatibel.html',''],
['Remote-control-Programm','r/remote-control-programm.html',''],
['Remote-Drucker','r/remote-drucker.html',''],
['Rendering','r/rendering.html',''],
['Report','r/report.html',''],
['Repository','r/repository.html',''],
['Requester','r/requester.html',''],
['Reserviertes Wort','r/reserviertes-wort.html',''],
['Reset','r/reset.html',''],
['Ressourcen','r/ressourcen.html',''],
['Restrukturierung','r/restrukturierung.html',''],
['Return','r/return.html',''],
['Return-Anweisung','r/return-anweisung.html',''],
['Reverse Engineering','r/reverse-engineering.html',''],
['RFC','r/rfc.html',''],
['RGB','r/rgb.html',''],
['Rightsizing','r/rightsizing.html',''],
['Ring-Topologie','r/ring-topologie.html',''],
['RISC-Prozessor','r/risc-prozessor.html',''],
['RLE','r/rle.html',''],
['RLL','r/rll.html',''],
['RLL-Festplatte','r/rll-festplatte.html',''],
['Roboter','r/roboter.html',''],
['Rollenspiele','r/rollenspiele.html',''],
['ROM','r/rom.html',''],
['Router','r/router.html',''],
['Routine','r/routine.html',''],
['RSA-System','r/rsa-system.html',''],
['RSI','r/rsi.html',''],
['RTF','r/rtf.html',''],
['RTS','r/rts.html',''],
['Rückruf bei Besetzt','r/rueckruf-bei-besetzt.html',''],
['Rufnummernübermittlung','r/rufnummernuebermittlung.html',''],
['Rufnummernunterdrückung','r/rufnummernunterdrueckung.html',''],
['Rufumleitung','r/rufumleitung.html',''],
['Run-Time-Version','r/run-time-version.html',''],
['S','s/s.html',''],
['S--Bus','s/s--bus.html',''],
['SAA','s/saa.html',''],
['Safe Mode','s/safe-mode.html',''],
['SAG','s/sag.html',''],
['SATA','s/sata.html',''],
['Scan-Code','s/scan-code.html',''],
['Scanner','s/scanner.html',''],
['Scheduler','s/scheduler.html',''],
['Schlafmodus','s/schlafmodus.html',''],
['Schleife','s/schleife.html',''],
['Schlitzmaskenröhre','s/schlitzmaskenroehre.html',''],
['Schnelltaste','s/schnelltaste.html',''],
['Schnittstelle','s/schnittstelle.html',''],
['Schreib-Lese-Kopf','s/schreib-lese-kopf.html',''],
['Schreibmaschinenseite','s/schreibmaschinenseite.html',''],
['Schriftart','s/schriftart.html',''],
['Schriftattribute','s/schriftattribute.html',''],
['Schriftgröße','s/schriftgroesse.html',''],
['Schroedinbug','s/schroedinbug.html',''],
['Schwedennorm','s/schwedennorm.html',''],
['SCR-Format','s/scr-format.html',''],
['Scrollen','s/scrollen.html',''],
['SCSI','s/scsi.html',''],
['SCSI-','s/scsi-.html',''],
['SCSI-','s/scsi-.html',''],
['SCSI-','s/scsi-.html',''],
['SDK','s/sdk.html',''],
['SDLC','s/sdlc.html',''],
['SDRAM','s/sdram.html',''],
['Second-Level-Cache','s/second-level-cache.html',''],
['Segment-Offset-Adressierung','s/segment-offset-adressierung.html',''],
['Seitenansicht','s/seitenansicht.html',''],
['Seitenbeschreibungssprache','s/seitenbeschreibungssprache.html',''],
['Seitenumbruch','s/seitenumbruch.html',''],
['Seitenverhältnis','s/seitenverhaeltnis.html',''],
['Sektorierung','s/sektorierung.html','selektives Backup','s/selektives-backup.html',''],
['Semantik','s/semantik.html',''],
['Semaphor','s/semaphor.html',''],
['SEO','s/seo-erklaerung.html',''],
['Sequentielle Datei','s/sequentielle-datei.html',''],
['Sequentieller Speicher','s/sequentieller-speicher.html',''],
['Serielle Schnittstelle','s/serielle-schnittstelle.html',''],
['Seriennummer','s/seriennummer.html',''],
['Serife','s/serife.html',''],
['Server','s/server.html',''],
['Service Pack','s/service-pack.html',''],
['SFT','s/sft.html',''],
['SGML','s/sgml.html',''],
['Shadow-RAM','s/shadow-ram.html',''],
['Shape','s/shape.html',''],
['Shared Memory','s/shared-memory.html',''],
['Shareware','s/shareware.html',''],
['Shell','s/shell.html',''],
['Shortcut','s/shortcut.html',''],
['Significant Digits','s/significant-digits.html',''],
['Signum','s/signum.html',''],
['Simplex','s/simplex.html',''],
['Simula','s/simula.html',''],
['Simulator','s/simulator.html',''],
['Skalieren','s/skalieren.html',''],
['Slack','s/slack.html',''],
['Slash','s/slash.html',''],
['Slimline','s/slimline.html',''],
['SLIP','s/slip.html',''],
['S.M.A.R.T.-System','s/smart-system.html',''],
['SMS','s/sms.html',''],
['SNA-Referenzmodell','s/sna-referenzmodell.html',''],
['SNA-Schichtenmodell','s/sna-schichtenmodell.html',''],
['Southbridge','s/southbridge.html',''],
['SPAM','s/spam.html',''],
['Spider','s/spider.html',''],
['Spoofing','s/spoofing.html',''],
['Spyware','s/spyware.html',''],
['Squeezing','s/squeezing.html',''],
['Standardanschluss','s/standardanschluss.html',''],
['Standleitung','s/standleitung.html',''],
['Statische Bindung','s/statische-bindung.html',''],
['Stealth-Virus','s/stealth-virus.html',''],
['Strichcode','s/strichcode.html',''],
['Struktogramm','s/struktogramm.html',''],
['Suchmaschinen-Marketing','s/suchmaschinen-marketing.html',''],
['Supersampling','s/supersampling.html',''],
['Tabellenkalkulationsprogramm','t/tabellenkalkulationsprogramm.html',''],
['Tabellensatz','t/tabellensatz.html',''],
['TAE','t/tae.html',''],
['Taktfrequenz','t/taktfrequenz.html',''],
['Taligent','t/taligent.html',''],
['TAN','t/tan.html',''],
['Taskbar','t/taskbar.html',''],
['Task-Switching','t/task-switching.html',''],
['Tastatur','t/tastatur.html',''],
['TBit','t/tbit.html',''],
['TByte','t/tbyte.html',''],
['TCO','t/tco.html',''],
['TCP/IP','t/tcp-ip.html',''],
['Telearbeit','t/telearbeit.html',''],
['Telekommunikation','t/telekommunikation.html',''],
['Telematik','t/telematik.html',''],
['Telix','t/telix.html',''],
['Telnet','t/telnet.html',''],
['Temporäre Datei','t/temporaere-datei.html',''],
['Terminal','t/terminal.html',''],
['Tesselation','t/tesselation.html',''],
['TeX','t/tex.html',''],
['Textbaustein','t/textbaustein.html',''],
['Textmarke','t/textmarke.html',''],
['Textprogramm','t/textprogramm.html',''],
['Textverarbeitung','t/textverarbeitung.html',''],
['Thermodrucker','t/thermodrucker.html',''],
['Thermopapier','t/thermopapier.html',''],
['Thermotransferdrucker','t/thermotransferdrucker.html',''],
['Thesaurus','t/thesaurus.html',''],
['Third-Level-Cache','t/third-level-cache.html',''],
['Thread','t/thread.html',''],
['Threeshot-Verfahren','t/threeshot-verfahren.html',''],
['Tick','t/tick.html',''],
['TIFF','t/tiff.html',''],
['Timeout','t/timeout.html',''],
['Time Sharing','t/time-sharing.html',''],
['Timeware','t/timeware.html',''],
['Tintenstrahldrucker','t/tintenstrahldrucker.html',''],
['Titelleiste','t/titelleiste.html',''],
['TK-Anlage','t/tk-anlage.html',''],
['Token','t/token.html',''],
['Token Passing','t/token-passing.html',''],
['Token Ring','t/token-ring.html',''],
['Toolbox','t/toolbox.html',''],
['Toolkit','t/toolkit.html',''],
['Top-down-Methode','t/top-down-methode.html',''],
['Topologie','t/topologie.html',''],
['Touchpad','t/touchpad.html',''],
['Touchpoint','t/touchpoint.html',''],
['Touchscreen','t/touchscreen.html',''],
['Tpi','t/tpi.html',''],
['Trace-back','t/trace-back.html',''],
['Tracing','t/tracing.html',''],
['Trackball','t/trackball.html',''],
['TrackPad','t/trackpad.html',''],
['Traktor','t/traktor.html',''],
['Transform & Lightning','t/transform-lightning.html',''],
['Transformer','t/transformer.html',''],
['Transistor','t/transistor.html',''],
['Translation Buffer','t/translation-buffer.html',''],
['Transpiler','t/transpiler.html',''],
['Transputer','t/transputer.html',''],
['Trashware','t/trashware.html',''],
['Trenddiagramm','t/trenddiagramm.html',''],
['Trial and Error','t/trial-and-error.html',''],
['Trilineare Filterung','t/trilineare-filterung.html',''],
['Trimmen','t/trimmen.html',''],
['Trinitron-Röhre','t/trinitron-roehre.html',''],
['Trojaner','t/trojaner.html',''],
['Trojanisches Pferd','t/trojanisches-pferd.html',''],
['TTL','t/ttl.html','']
];
console.log(sites.length);
/*
var links = [];
$('td a').each(function() {if(this.href.indexOf("a/")){
   links.push( this.text,this.href);} 
   var href = this.href;
});
*/
var more_entries = new Array();
var last_entries = new Array();
var rando_more = new Array();
var rando_last = new Array();
var moreHTML ='';
var lastHTML ='<ul class="pure-menu-list"><li class="pure-menu-item" style="padding-top: 5px;"><span class=""  style="padding: 7px 0px 0px 12px;height: 24px;">Letzte Einträge</span></li></ul>';
for (var a=0;a<6;a++)
{
var rando_l = Math.floor((Math.random() * last.length) + 0);
var rando_m = Math.floor((Math.random() * sites.length) + 0);
if(!in_array(rando_l,rando_last)){rando_last.push(rando_l);
last_entries.push(new Array(last[rando_l][0],last[rando_l][1],last[rando_l][2]));
}
if(!in_array(rando_m,rando_more)){rando_more.push(rando_m);
more_entries.push(new Array(sites[rando_m][0],sites[rando_m][1],sites[rando_m][2]));
}
}
for(var b=0;b<more_entries.length;b++){/*console.log(more_entries[b]);*/moreHTML += "<a href='http://www.bullhost.de/"+more_entries[b][1]+"' title='"+more_entries[b][0]+"'>Definition bzw. Erklärung: "+more_entries[b][0]+"</a><br/>";}
for(var c=0;c<last_entries.length;c++){/*console.log(last_entries[c]);*/lastHTML += "<a href='http://www.bullhost.de/"+last_entries[c][1]+"' title='"+last_entries[c][0]+"' style='padding: 2px 0px 4px 12px;height: 18px;'> • "+last_entries[c][0]+"</a><br/>";}
(function () {
document.getElementById('more_entries').innerHTML =moreHTML;
document.getElementById('last_entries').innerHTML =lastHTML;
})();
